name: flutter_custom_paint_map
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.1
  geojson: ^1.0.0
  hooks_riverpod: ^2.1.1
  latlong2: ^0.8.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  pedantic_mono: ^1.19.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/maps/
